# docker-image.yml
name: winepy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: idiotdocker
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: idiotdocker/winepy
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=test,enable=${{ github.ref == format('refs/heads/{0}', 'test') }}
            type=raw,value=dev,enable=${{ github.ref == format('refs/heads/{0}', 'dev') }}

      - name: Build and push
        uses: docker/build-push-action@v3 # docker build & push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: idiotdocker
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: idiotdocker/winepy
          short-description: ${{ github.event.repository.description }}
