# docker-image.yml
name: Publish Wine-Python

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: idiotdocker
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: idiotdocker/winepy
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2 # docker build & push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}